apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tkfgvi64u-nodejs 
  janus-idp.io/tekton: tkfgvi64u-nodejs
  backstage.io/kubernetes-id: tkfgvi64u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkfgvi64u-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml